overrides:
  debug@>=4.0.0 <4.3.1: '>=4.3.1'
  tar@<6.2.1: '>=6.2.1'
  semver@>=7.0.0 <7.5.2: '>=7.5.2'
  undici@>=4.5.0 <5.28.5: '>=5.28.5'
  path-to-regexp@>=4.0.0 <6.3.0: '>=6.3.0'
  esbuild@<=0.24.2: '>=0.25.0'
  cookie@<0.7.0: '>=0.7.0'
  undici@<5.29.0: '>=5.29.0'
